{{- $ns := include "ns.name" . -}}
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-intra-namespace
  namespace: {{ $ns }}
  labels:
    {{- include "ns.policy.labels" (dict "root" . "policyName" "allow-intra-namespace") | nindent 4 }}
spec:
  description: "Allow all traffic within the same namespace"
  endpointSelector: {}
  ingress:
    - fromEndpoints:
        - {}
  egress:
    - toEndpoints:
        - {}
