{{- $ns := include "ns.name" . -}}
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-intra-namespace
  namespace: {{ $ns }}
  labels:
    {{- include "ns.labels" . | nindent 4 }}
    claro.com.br/policy-name: "allow-intra-namespace"
spec:
  description: "Allow all traffic within the same namespace"
  endpointSelector: {}
  ingress:
    - fromEndpoints:
        - {}
  egress:
    - toEndpoints:
        - {}
