{{- $ns := include "ns.name" . -}}
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: default-deny
  namespace: {{ $ns }}
  labels:
    {{- include "ns.policy.labels" (dict "root" . "policyName" "default-deny") | nindent 4 }}
spec:
  description: "Default deny — bloqueia todo ingress"
  endpointSelector: {}
  ingress: []
