{{- $ns := include "ns.name" . -}}
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: default-deny
  namespace: {{ $ns }}
  labels:
    {{- include "ns.labels" . | nindent 4 }}
    claro.com.br/policy-name: "default-deny"
spec:
  description: "Default deny — bloqueia todo ingress"
  endpointSelector: {}
  ingress: []
